### ISSUE TITLE
刷新会闪现vue默认界面

### ISSUE THREAD

**Issue by 593496637** [LeoKun1231/power-system-visualization#2]
1.网页刷新会闪现vue默认界面
2.chart图不清晰，有点模糊

**Comment by LeoKun1231** [comment]
第一种情况能截个图吗？我这边一切正常

**Comment by LeoKun1231** [comment]
> 1.网页刷新会闪现vue默认界面 2.chart图不清晰，有点模糊
第一种情况能截个图吗？我这边一切正常

**Comment by LeoKun1231** [comment]
第一种情况能截图吗？我这边复现不了

**Comment by 593496637** [comment]
1 可能是其他缓存影响，目前没有发现这个问题了
